language: go
go:
    - 1.9
before_install:
    - go get github.com/songgao/water
install:
    - go get github.com/ICKelin/opennotr/notrd
    - go get github.com/ICKelin/opennotr/notr
before_script:
script:
    - cd $HOME/gopath/src/github.com/ICKelin/opennotr
    - ./build.sh

